apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale
  namespace: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 20
